enum CharacterActionTypes {
  FILTERED_MENTORS_WITH_QUERY_REQUEST = 'filteredMentors/FILTERED_MENTORS_WITH_QUERY_REQUEST',
  FILTERED_MENTORS_WITH_QUERY_SUCCESS = 'filteredMentors/FILTERED_MENTORS_WITH_QUERY_SUCCESS',
  FILTERED_MENTORS_WITH_QUERY_ERROR = 'filteredMentors/FILTERED_MENTORS_WITH_QUERY_ERROR',
}

export default CharacterActionTypes;
